name: .NET Core Desktop

on:
  #push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [ubuntu-latest]  
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core 3.1 
      uses: actions/setup-dotnet@v1
      with:
            dotnet-version: 3.1.x
            
    - name: Install .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
            dotnet-version: 5.0.x
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet packages
      run: nuget restore eBanking/eBanking.sln

    - name: Building
      run: dotnet build --configuration Release ./eBanking    

    - name: Executing unit tests
      run: dotnet test eBanking/eBanking.Tests
      
    - name: Executing integration tests
      run: dotnet test eBanking/eBanking.IntegrationTests

    - name: Publishing
      run: |
        cd eBanking
        ls
        dotnet publish
        cd ./eBanking/bin/Debug/netcoreapp3.1/publish/
        rm appsettings.json
        rm -r cs de es fr it ja ko pl ru zh-Hans zh-Hant tr pt-BR
        ls
    
    - name: Deploying
      uses: garygrossgarten/github-action-scp@v0.7.3
      with:
          local: './eBanking/eBanking/bin/Debug/netcoreapp3.1/publish/'
          remote: '/home/miki/GithubActionsPublish'
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          
#    - name: Starting application
#      uses: garygrossgarten/github-action-ssh@v0.6.3
#      with:
#        command: |        
#          cd /home/miki/GithubActionsPublish
#          killall screen
#          rm LoggerFile.json
#          rm investmentChartData.json          
#          screen -d -m dotnet eBanking.dll        
#        host: ${{ secrets.SSH_HOST }}
#        username: ${{ secrets.SSH_USERNAME }}
#        password: ${{ secrets.SSH_PASSWORD }}
