name: .NET Core Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: [windows-latest]  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
  
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet packages
      run: nuget restore eBanking\eBanking.sln
      
    - name: Build the Solution
      run: msbuild eBanking\eBanking.sln        
        
    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test eBanking\eBanking.Tests
      
    - name: vs test solution
      uses: tonyhallett/vstest-solution-action@v1.0.0
      with:
        solution: eBanking\eBanking.sln
